import { FC, ReactNode } from 'react'
import type { Metadata } from 'next'
import RootTemplateLayout from '../application/layout/RootLayout'
import '@/application/styles/global.scss'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

interface RootLayoutState {
    children: ReactNode
}


const RootLayout: FC<RootLayoutState> = props => {
    const { children } = props

    return (
        <RootTemplateLayout>
            {children}
        </RootTemplateLayout>
    )
}

export default RootLayout