import { FC, ReactNode } from 'react'
import type { Metadata } from 'next'
import { RootTemplateLayout } from '@/application/layout/RootTemplateLayout'
import '@/application/styles/global.scss'


export const metadata: Metadata = {
    title: 'MangoRead',
    description: 'Generated by create next app',
}

interface RootLayoutState {
    children: ReactNode
}


const RootLayout: FC<RootLayoutState> = props => {
    const { children } = props

    return (
        <RootTemplateLayout>
            {children}
        </RootTemplateLayout>
    )
}

export default RootLayout